name: 'CI'

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup nodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: | # Install and link dependencies
          npm ci
          npx lerna bootstrap

      - name: Run tests # Run tests of all packages
          run: npm run test
